/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*Base address for System handler control status register */

uint32_t *pSHCSR = (uint32_t *)0xE000ED24;


int main(void)
{

	/*Enable the faults in SHCSR */

	*pSHCSR |= (1<<18); /*Usage fault */
	*pSHCSR |= (1<<17); /*Bus fault */
	*pSHCSR |= (1<<16); /*Mem fault */

	/* Trigger the fault by meeting certain conditions */
	uint32_t *pUnexpected_Instruction = (uint32_t *)0x20001000;
	*pUnexpected_Instruction = 0xFFFFFFFF;

	void (*some_function_pointer)(void);
	some_function_pointer = (void *)0x20001000;

	some_function_pointer();

    /* Loop forever */
	for(;;);
}

void MemManage_Handler(void) {
	printf("MemManage Fault Handler\n");
	while(1);

}

void BusFault_Handler(void) {
	printf("Bus Fault Handler\n");
	while(1);

}

__attribute__((naked)) void UsageFault_Handler(void) {
	/* Copy the MSP value to register r4 */
	__asm volatile("MRS r0, MSP");

	/*Branch to the C function */
	__asm volatile("B UsageFault_Handler_c");

}

/* According to Procedure call standards, r0 will be used as the first argument in the callee */

void UsageFault_Handler_c(uint32_t *pBaseStackFrame_from_asm) {

	printf("Usage Fault Handler\n");

	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Fault Status Contents = %lx\n", ((*pUFSR) & 0xFFFF));

	printf("Base Stack Frame Address  = %p\n", pBaseStackFrame_from_asm);
	printf("Value of R0  = %lx\n", pBaseStackFrame_from_asm[0]);
	printf("Value of R1  = %lx\n", pBaseStackFrame_from_asm[1]);
	printf("Value of R2  = %lx\n", pBaseStackFrame_from_asm[2]);
	printf("Value of R3  = %lx\n", pBaseStackFrame_from_asm[3]);
	printf("Value of R12  = %lx\n", pBaseStackFrame_from_asm[4]);
	printf("Value of LR  = %lx\n", pBaseStackFrame_from_asm[5]);
	printf("Value of PC  = %lx\n", pBaseStackFrame_from_asm[6]);
	printf("Value of XPSR  = %lx\n", pBaseStackFrame_from_asm[7]);


	while(1);

}
