/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
#if 0
    /* Loop forever */
	int var = 1;
	__asm volatile ("MOV R0, %0"::"r"(var));

	/* Constraint string = "r"
	 * Constraint modififer = "="
	 */
	int control_register = 24;
	__asm volatile ("MRS %0, CONTROL":"=r"(control_register));

	/*Copy Content of C variable from one to another */
	int var_1 = 10, var_2;
	__asm volatile ("MOV %0, %1": "=r"(var_2): "r"(var_1));

#endif
	/*Copy Content of a pointer into a C variable using registers*/
	int variable, *ptr;
	ptr = (int *)0x20001000;
	__asm volatile ("LDR %0, [%1]": "=r"(variable): "r"(ptr));


	for(;;);
}
