/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*Mathematical operation functions */

int32_t addition(int32_t x, int32_t y) {

	__asm volatile("SVC #36");

	int32_t result;
	__asm volatile("MOV %0, R0": "=r"(result));
	return result;

}

int32_t subtraction(int32_t x, int32_t y) {
	__asm volatile("SVC #37");

	int32_t result;
	__asm volatile("MOV %0, R0": "=r"(result));
	return result;

}

int32_t multiply(int32_t x, int32_t y) {
	__asm volatile("SVC #38");

	int32_t result;
	__asm volatile("MOV %0, R0": "=r"(result));
	return result;;
}


int32_t division(int32_t x, int32_t y) {
	__asm volatile("SVC #39");

	int32_t result;
	__asm volatile("MOV %0, R0": "=r"(result));
	return result;
}

int main(void)
{

	printf("Addition Result = %d\n", addition(20, -10));
	printf("Subtraction Result = %d\n", subtraction(20, -10));
	printf("Multiplication Result = %d\n", multiply(20, -10));
	printf("Division Result = %d\n", division(20, -10));


	/* Loop forever */
	for(;;);
}


__attribute__((naked)) void SVC_Handler(void) {
	__asm ("MRS R0, MSP");
	__asm ("B SVC_Handler_c");
}


void SVC_Handler_c(uint32_t *pBaseStackAddress){
	printf("Inside SVC Handler C function\n");

	uint8_t *pcaddress = (uint8_t *)pBaseStackAddress[6];
	pcaddress -= 2;

	uint8_t svc_number = *pcaddress;
	printf("SVC address = %d\n", svc_number);

	switch(svc_number){
	case 36:
		pBaseStackAddress[0] = pBaseStackAddress[0] + pBaseStackAddress[1];
		break;
	case 37:
		pBaseStackAddress[0] = pBaseStackAddress[0] - pBaseStackAddress[1];
		break;
	case 38:
		pBaseStackAddress[0] = pBaseStackAddress[0] * pBaseStackAddress[1];
		break;
	case 39:
		pBaseStackAddress[0] = pBaseStackAddress[0] / pBaseStackAddress[1];
		break;
	}
}
