/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RAM_START 0x20000000U
#define RAM_SIZE (40 * 1024)
#define RAM_END (RAM_START + RAM_SIZE)

#define MSP_START RAM_END
#define MSP_END (MSP_START - 512)
#define PSP_START MSP_END
#define PSP_END (PSP_START - 512)

int function_addition(int a, int b, int c){
	return a + b + c;
}

__attribute__((naked)) void change_sp_to_psp(void) {

	__asm volatile(".equ SRAM_END, (0x20000000 + (40 *1024))");
	__asm volatile(".equ PSP_START, (SRAM_END - 512)");
	__asm volatile("LDR R0, =PSP_START");
	__asm volatile("MSR PSP, R0");
	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL, R0");
	__asm volatile("BX LR");
}

int main(void)
{
	/*Change the Stack pointer mode to PSP */
	change_sp_to_psp();

	/* Function now uses the PSP */
	function_addition(1, 2, 3);

	/* Generate the Exception to see the use the MSP in handler mode*/

	__asm volatile("SVC #0x3");

	/* Loop forever */
	for(;;);
}

/*SVC exception handler, decalred in Startup.S, implemented here */

void SVC_Handler(void){
	printf("Handler Mode, using MSP");
}
